Carts/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carts.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }

        //取得目前購物車頁面
        public ActionResult GetCart()
        {
            return PartialView("_CartPartial");
        }

        //以id加入Product至購物車，並回傳購物車頁面
        public ActionResult AddToCart(int id)
        {
            var currentCart = Models.Cart.Operation.GetCurrentCart();
            currentCart.AddProduct(id);
            return PartialView("_CartPartial");
        }

        public ActionResult RemoveFromCart(int id)
        {
            var currentCart = Models.Cart.Operation.GetCurrentCart();
            currentCart.RemoveProduct(id);
            return PartialView("_CartPartial");
        }

        public ActionResult ClearCart()
        {
            var currentCart = Models.Cart.Operation.GetCurrentCart();
            currentCart.ClearCart();
            return PartialView("_CartPartial");
        }

    }
}

Carts/Controllers/ManageOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carts.Controllers
{
    public class ManageOrderController : Controller
    {
        // GET: ManageOrder
        public ActionResult Index()
        {
            using(Models.CartsEntities db = new Models.CartsEntities())
            {
                var result = (from s in db.Orders select s).ToList();
                return View(result);
            }
        }

        public ActionResult Details(int id)
        {
            using (Models.CartsEntities db = new Models.CartsEntities())
            {
                var result = (from s in db.OrderDetails where s.OrderId == id select s).ToList();

                if (result.Count == 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(result);
                }
            }
        }
    }
}

Carts/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carts.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Models.OrderModel.Ship postback)
        {
            if(this.ModelState.IsValid)
            {
                var currentcart = Models.Cart.Operation.GetCurrentCart();

                var userId = "1111";
                using (Models.CartsEntities db = new Models.CartsEntities())
                {
                    var order = new Models.Order()
                    {
                        UserId = userId,
                        RecieverName = postback.RecieverName,
                        RecieverPhone = postback.RecieverPhone,
                        RecieverAddress = postback.RecieverAdress
                    };

                    db.Orders.Add(order);
                    db.SaveChanges();

                    var orderDetails = currentcart.ToOrderDetailList(order.Id);

                    db.OrderDetails.AddRange(orderDetails);
                    db.SaveChanges();
                }
                return Content("訂購成功");
            }            
            
            return View();
        }
    }
}

Carts/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carts.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            //宣告回傳商品列表result
            List<Models.Product> result = new List<Models.Product>();

            //接收轉導的成功訊息
            ViewBag.ResultMessage = TempData["ResultMessage"];

            //使用CartsEntities類別，名稱為db
            using( Models.CartsEntities db = new Models.CartsEntities() )
            {
                //使用LinQ語法抓取目前Products資料庫中所有資料
                result = (from s in db.Products select s).ToList();

                //將result傳送給檢視
                return View(result);
            }
        }

        //建立商品頁面
        public ActionResult Create()
        {
            return View();
        }

        //建立商品頁面 - 資料傳回處理
        [HttpPost] //指定只有使用POST方法才可進入
        public ActionResult Create( Models.Product postback)
        {
            if (this.ModelState.IsValid) //如果資料驗證成功
            {
                using (Models.CartsEntities db = new Models.CartsEntities())
                {
                    //將回傳資料postback加入至Products
                    db.Products.Add(postback);

                    //儲存異動資料
                    db.SaveChanges();

                    //設定成功訊息
                    TempData["ResultMessage"] = String.Format("商品[{0}]成功建立", postback.Name);

                    //轉導Product/Index頁面
                    return RedirectToAction("Index");
                }
            }
            //失敗訊息
            ViewBag.ResultMessage = "資料有誤，請檢查";

            //停留在Create頁面
            return View(postback);
        }


        //編輯商品頁面
        public ActionResult Edit(int id)
        {
            using (Models.CartsEntities db = new Models.CartsEntities())
            {
                //抓取Product.Id等於輸入id的資料
                var result = (from s in db.Products where s.Id == id select s).FirstOrDefault();
                if( result != default( Models.Product ) ) //判斷此id是否有資料
                {
                    return View(result); //如果有回傳編輯商品頁面
                }
                else
                {   //如果沒有資料則顯示錯誤訊息並導回Index頁面
                    TempData["resultMessage"] = "資料有誤，請重新操作";
                    return RedirectToAction("Index");
                }
            }
        }

        //編輯商品頁面 - 資料傳回處理
        [HttpPost]
        public ActionResult Edit(Models.Product postback)
        {
            if( this.ModelState.IsValid ) //判斷使用者輸入資料是否正確
            {
                using (Models.CartsEntities db = new Models.CartsEntities())
                {
                    //抓取Product.Id等於回傳postback.Id的資料
                    var result = (from s in db.Products where s.Id == postback.Id select s).FirstOrDefault();

                    //儲存使用者變更資料
                    result.Name = postback.Name;                        result.Price = postback.Price;
                    result.PublishDate = postback.PublishDate;          result.Quantity = postback.Quantity;
                    result.Status = postback.Status;                    result.CategoryId = postback.CategoryId;
                    result.DefaultImageId = postback.DefaultImageId;    result.Description = postback.Description;
                    result.DefaultImageURL = postback.DefaultImageURL;
                    //儲存所有變更
                    db.SaveChanges();

                    //設定成功訊息並導回index頁面
                    TempData["ResultMessage"] = String.Format("商品[{0}]成功編輯", postback.Name);
                    return RedirectToAction("Index");
                }
            }
            else //如果資料不正確則導向自己(Edit頁面)
            {
                return View(postback);
            }
        }

        //刪除商品
        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (Models.CartsEntities db = new Models.CartsEntities())
            {
                //抓取Product.Id等於輸入id的資料
                var result = (from s in db.Products where s.Id == id select s).FirstOrDefault();
                if( result != default( Models.Product ) ) //判斷此id是否有資料
                {
                    db.Products.Remove(result);

                    //儲存所有變更
                    db.SaveChanges();

                    //設定成功訊息並導回index頁面
                    TempData["ResultMessage"] = String.Format("商品[{0}]成功刪除", result.Name);
                    return RedirectToAction("Index");
                }
                else
                {   //如果沒有資料則顯示錯誤訊息並導回Index頁面
                    TempData["resultMessage"] = "指定資料不存在，無法刪除，請重新操作";
                    return RedirectToAction("Index");
                }
            }
        }













    }
}

Carts/Views/Shared/_CartPartial.cshtml
@{
    //取得當前購物車所有內容
    var currentCart = Carts.Models.Cart.Operation.GetCurrentCart();
}
<a id="CartDropDown" class="dropdown-toggle" data-toggle="dropdown">
    @String.Format("共{0}元 ({1})", currentCart.TotalAmount, currentCart.Count)
    <span class="caret"></span>
</a>
<ul class="dropdown-menu Cart" role="menu" aria-labelledby="CartDropDown">
    @if (currentCart.Count > 0)
    {
        foreach (var cartitem in currentCart)
        {
            //依序輸出 : <li><a>可愛橡皮擦 <span>50元 X 2</span></a></li>
            <li class="col-xs-12">
                <span class="col-xs-9">@cartitem.Name @cartitem.Price.ToString("0.0") 元 X @cartitem.Quantity </span>
                <span class="btn btn-danger col-xs-2" onclick="RemoveFromCart('@cartitem.Id')">
                    X
                </span>
            </li>
        }
        <li class="divider"></li>
        <li>
            <div id="CartButtons" class="col-xs-12">
                <a class="btn btn-success text-center col-xs-5" href="@Url.Action("Index","Order",new { })">
                    結帳去
                </a>
                <a class="btn btn-danger text-center  col-xs-5" onclick="ClearCart()">清空</a>
            </div>
        </li>
    }
    else
    {
        <li><a class="btn btn-default text-center" href="#">購物車無任何商品</a></li>
    }

</ul>

Carts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @* 購物車Js *@
<script type="text/javascript">
        //網頁載入完成時執行之function
        $(document).ready(function () {
            console.log("ready!");
        });

        //加入編號為productId的商品進購物車
        function AddToCart(productId) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("AddToCart", "Cart")',
                data: { id: productId }
            })
            .done(function (msg) {
                //將回傳的購物車頁面 填入 li#Cart
                $('li#Cart').html(msg);
            });
        }

        function RemoveFromCart(productId) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("RemoveFromCart", "Cart")',
                data: { id: productId }
            })
            .done(function (msg) {
                //將回傳的購物車頁面 填入 li#Cart
                $('li#Cart').html(msg);
            });
    }

            function ClearCart() {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ClearCart", "Cart")',
                data: {}
            })
            .done(function (msg) {
                //將回傳的購物車頁面 填入 li#Cart
                $('li#Cart').html(msg);
            });
        }



</script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("IT鐵人購物網站", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡方式", "Contact", "Home")</li>
                    <li>@Html.ActionLink("商品管理", "Index", "Product")</li>
                    <li>@Html.ActionLink("會員管理", "Index", "ManageUser")</li>
                    <li>@Html.ActionLink("訂單管理", "Index", "ManageOrder")</li>
                    <li id="Cart">
                        @Html.Partial("_CartPartial")
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>
</body>
</html>